name: Auto Deploy Hexo to GitHub Pages

on: # 触发条件
  push:
    branches: [master]
  workflow_dispatch: # 手动按钮

permissions: # 给 Actions 写 Pages 的权限
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉源码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # 主题用 submodule 时必加

      # 2. 装 Node 20（2025 LTS）
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: npm run clean
      - run: npm run build # 对应 package.json 里 "build": "hexo generate"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 5. 部署到 gh-pages 分支
      - name: Deploy
        uses: actions/deploy-pages@v4
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: ./public
        #   publish_branch: gh-pages
        # cname: | # 如果有自定义域名，把 xxx.com 换成你的
        #   xxx.com
